### ISSUE TITLE
Additional Tags on Ores

### ISSUE THREAD

**Issue by NillerMedDild** [Qmunity/BluePower#516]
Hello!

I would like to request that all ores from Blue Power are added to the `forge:ores` tag - Preferably both block and item tags.
This would allow me to filter by all ores for a config in Ore Excavation.

I hope you'll consider it :)

**Comment by MoreThanHidden** [comment]
Ok no worries this is similar to #487 I'll take a look after work.

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.154-alpha now available on curse.

**Comment by NillerMedDild** [comment]
Thanks!

**Comment by Halfdeaf** [comment]
Looks like some ores are still missing the forge:ores tag, mainly the gems and teslatite

**Comment by MoreThanHidden** [comment]
What version are you using looks fine to me 
![image](https://user-images.githubusercontent.com/1351964/69490517-309a0300-0ec4-11ea-8e85-8b4bc44eecc5.png)
